Repository Yashika1410/Code-base-2022, pull requests merged in 2022-10, with the labels that each got.

#7 created BMI Calculator
  bmi-calculator/.gitignore
  bmi-calculator/package-lock.json
  bmi-calculator/package.json
  bmi-calculator/public/calculator.png
  bmi-calculator/public/index.html
  bmi-calculator/public/styles.css
  bmi-calculator/src/components/App.jsx
  bmi-calculator/src/components/Body.jsx
  bmi-calculator/src/components/Footer.jsx
  bmi-calculator/src/components/Header.jsx
  bmi-calculator/src/components/calculator.gif
  bmi-calculator/src/index.js
  contributors.md
Labels: hacktoberfest-accepted

#12 Todo Full stack application
  Todo Full Stack Aplication (Flask python)/app.py
  Todo Full Stack Aplication (Flask python)/cc.log
  Todo Full Stack Aplication (Flask python)/middleware.py
  Todo Full Stack Aplication (Flask python)/pic/1.png
  Todo Full Stack Aplication (Flask python)/pic/2.png
  Todo Full Stack Aplication (Flask python)/pic/3.png
  Todo Full Stack Aplication (Flask python)/pic/4.png
  Todo Full Stack Aplication (Flask python)/readme.md
  Todo Full Stack Aplication (Flask python)/requirements.txt
  Todo Full Stack Aplication (Flask python)/static/home.css
  Todo Full Stack Aplication (Flask python)/templates/index.html
  Todo Full Stack Aplication (Flask python)/templates/update.html
  Todo Full Stack Aplication (Flask python)/todo.db
Labels: hacktoberfest-accepted, Accepted

#9 todo_react
  Contact-Manager/package-lock.json
  Contact-Manager/package.json
  Contact-Manager/public/index.html
  Contact-Manager/src/api/contacts.js
  Contact-Manager/src/components/AddContact.js
  Contact-Manager/src/components/App.js
  Contact-Manager/src/components/ContactCard.js
  Contact-Manager/src/components/ContactList.js
  Contact-Manager/src/components/EditContact.js
  Contact-Manager/src/components/Header.js
  Contact-Manager/src/components/Untitled-1.txt
  Contact-Manager/src/index.js
  Contact-Manager/src/style.css
  Todo-React/README.md
  Todo-React/package-lock.json
  Todo-React/package.json
  Todo-React/public/favicon.ico
  Todo-React/public/index.html
  Todo-React/public/logo192.png
  Todo-React/public/logo512.png
  Todo-React/public/manifest.json
  Todo-React/public/robots.txt
  Todo-React/src/App.js
  Todo-React/src/Index.module.css
  Todo-React/src/components/TodoEdit.js
  Todo-React/src/components/TodoInput.js
  Todo-React/src/components/TodoInput.module.css
  Todo-React/src/components/TodoItem.js
  Todo-React/src/components/TodoItem.module.css
  Todo-React/src/components/TodoList.js
  Todo-React/src/index.js
Labels: hacktoberfest-accepted

#14 Updated style.css using css properties
  css/style.css
Labels: hacktoberfest-accepted

#17 Weather Application
  contributors.md
  weather app/index.css
  weather app/index.html
  weather app/index.js
  weather app/readme.md
Labels: hacktoberfest-accepted

#18 Added Simon Game
  Simon Game/README.md
  Simon Game/game.js
  Simon Game/images/background.jpg
  Simon Game/index.html
  Simon Game/sounds/blue.mp3
  Simon Game/sounds/green.mp3
  Simon Game/sounds/red.mp3
  Simon Game/sounds/wrong.mp3
  Simon Game/sounds/yellow.mp3
  Simon Game/styles.css
Labels: hacktoberfest-accepted

#19 DrumKit
  Drum-Kit/README.md
  Drum-Kit/imm/crash.png
  Drum-Kit/imm/kick.png
  Drum-Kit/imm/snare.png
  Drum-Kit/imm/temp.html
  Drum-Kit/imm/tom1.png
  Drum-Kit/imm/tom2.png
  Drum-Kit/imm/tom3.png
  Drum-Kit/imm/tom4.png
  Drum-Kit/index.html
  Drum-Kit/index.js
  Drum-Kit/snd/kick-bass.mp3
  Drum-Kit/snd/snare.mp3
  Drum-Kit/snd/temp.html
  Drum-Kit/snd/tom-1.mp3
  Drum-Kit/snd/tom-2.mp3
  Drum-Kit/snd/tom-3.mp3
  Drum-Kit/snd/tom-4.mp3
  Drum-Kit/styles.css
Labels: hacktoberfest-accepted

#24 Pomodoro Timer App with JavaScript
  Pomodoro-Timer/README.md
  Pomodoro-Timer/backtowork.mp3
  Pomodoro-Timer/break.mp3
  Pomodoro-Timer/button-sound.mp3
  Pomodoro-Timer/index.html
  Pomodoro-Timer/main.js
  Pomodoro-Timer/package-lock.json
  Pomodoro-Timer/package.json
  Pomodoro-Timer/styles.css
  contributors.md
Labels: hacktoberfest-accepted

#27 weather website
  contributors.md
  web_server/package-lock.json
  web_server/package.json
  web_server/public/css/style.css
  web_server/public/img/canIHelpYou.png
  web_server/public/img/lost.jpg
  web_server/public/img/my_current_pic.jpg
  web_server/public/img/my_pic.jpg
  web_server/public/img/weather.png
  web_server/public/img/whatHappened.jpeg
  web_server/public/img/whatHappened.jpg
  web_server/public/js/app.js
  web_server/public/js/weather.js
  web_server/src/app.js
  web_server/src/style.css
  web_server/src/utils/forecast.js
  web_server/src/utils/geocode.js
  web_server/templates/partials/footer.hbs
  web_server/templates/partials/header.hbs
  web_server/templates/views/404.hbs
  web_server/templates/views/about.hbs
  web_server/templates/views/help.hbs
  web_server/templates/views/index.hbs
Labels: hacktoberfest-accepted

#30 added Mr.Robot quiz project
  Mr.Robot-Quiz/index.html
  Mr.Robot-Quiz/quiz.js
  Mr.Robot-Quiz/styles.css
  contributors.md
Labels: hacktoberfest-accepted

#35 Added a github finder project
  Github Finder/app.js
  Github Finder/bootstrap.min.css
  Github Finder/bootstrap2.min.css
  Github Finder/bootstrap3.min.css
  Github Finder/github.js
  Github Finder/index.html
  Github Finder/ui.js
  contributors.md
Labels: hacktoberfest-accepted

#38 Added currency converter
  Currency Converter/README.md
  Currency Converter/currency.css
  Currency Converter/currency.js
  Currency Converter/index.html
  contributors.md
Labels: hacktoberfest-accepted

#31 A JavaScript clock.
  A js clock/Clock.css
  A js clock/Clock.html
  A js clock/Clock.js
  A js clock/Images/beautiful-tropical-beach-sea-ocean-with-white-cloud-blue-sky-background-travel-vacation-trip.jpg
  A js clock/Images/clock(2).png
  A js clock/Readme.md
  contributors.md
Labels: hacktoberfest-accepted

#41 A calculated with voice operating features
  Voice-Operated-Calculator/index.html
  Voice-Operated-Calculator/logo.png
  Voice-Operated-Calculator/mic.png
  Voice-Operated-Calculator/responsivevoice.js
  Voice-Operated-Calculator/script.js
  Voice-Operated-Calculator/style.css
  contributors.md
Labels: hacktoberfest-accepted

#34 Added JavaScript Instumental Kit
  JavaScript Instrument Kit/background.jpg
  JavaScript Instrument Kit/index-FINISHED.html
  JavaScript Instrument Kit/index-START.html
  JavaScript Instrument Kit/sounds/boom.wav
  JavaScript Instrument Kit/sounds/clap.wav
  JavaScript Instrument Kit/sounds/hihat.wav
  JavaScript Instrument Kit/sounds/kick.wav
  JavaScript Instrument Kit/sounds/openhat.wav
  JavaScript Instrument Kit/sounds/ride.wav
  JavaScript Instrument Kit/sounds/snare.wav
  JavaScript Instrument Kit/sounds/tink.wav
  JavaScript Instrument Kit/sounds/tom.wav
  JavaScript Instrument Kit/style.css
  contributors.md
Labels: hacktoberfest-accepted, Accepted

#40 Todo react UI
  React Projects/Todo-React/.gitignore
  React Projects/Todo-React/package-lock.json
  React Projects/Todo-React/src/components/TodoInput.js
  React Projects/Todo-React/src/components/TodoInput.module.css
  React Projects/Todo-React/src/components/TodoItem.js
  React Projects/Todo-React/src/components/TodoItem.module.css
  contributors.md
Labels: hacktoberfest-accepted

#60 Added Random Password Generator Project
  HTML_CSS_JS Projects/Random Password Generator/Readme.md
  HTML_CSS_JS Projects/Random Password Generator/images/preview.png
  HTML_CSS_JS Projects/Random Password Generator/index.html
  HTML_CSS_JS Projects/Random Password Generator/main.js
  HTML_CSS_JS Projects/Random Password Generator/style.css
  contributors.md
Labels: hacktoberfest-accepted, hacktoberfest

#61 Solved SqlAlchemy issue
  Flask Projects/Todo Full Stack Aplication/app.py
  Flask Projects/Todo Full Stack Aplication/instance/todo.db
  Flask Projects/Todo Full Stack Aplication/static/home.css
  Flask Projects/Todo Full Stack Aplication/templates/index.html
  Flask Projects/Todo Full Stack Aplication/todo.db
Labels: hacktoberfest-accepted, hacktoberfest

#76 Add Rock Paper Scissors game
  HTML_CSS_JS Projects/Rock Paper & Scissors game/README.md
  HTML_CSS_JS Projects/Rock Paper & Scissors game/index.html
  HTML_CSS_JS Projects/Rock Paper & Scissors game/rock paper scissors javascript project.png
  contributors.md
Labels: Accepted, hacktoberfest

#85 responsive navbar created in Reactjs and Material-UI
  Responvsive Navbar/.gitignore
  Responvsive Navbar/package-lock.json
  Responvsive Navbar/package.json
  Responvsive Navbar/public/index.html
  Responvsive Navbar/public/manifest.json
  Responvsive Navbar/public/robots.txt
  Responvsive Navbar/src/App.js
  Responvsive Navbar/src/Components/About.js
  Responvsive Navbar/src/Components/Home.js
  Responvsive Navbar/src/Components/NavBar.js
  Responvsive Navbar/src/Components/Projects.js
  Responvsive Navbar/src/Components/Theme.js
  Responvsive Navbar/src/assets/about_head.svg
  Responvsive Navbar/src/assets/about_stack.svg
  Responvsive Navbar/src/assets/external-link-logo.svg
  Responvsive Navbar/src/assets/github-logo.png
  Responvsive Navbar/src/assets/home.svg
  Responvsive Navbar/src/assets/home2.svg
  Responvsive Navbar/src/assets/project-images/blood-donation.png
  Responvsive Navbar/src/assets/project-images/form-handler.png
  Responvsive Navbar/src/assets/project-images/library.png
  Responvsive Navbar/src/assets/project-images/vaccine.png
  Responvsive Navbar/src/assets/project-images/weather-app.png
  Responvsive Navbar/src/assets/socials.svg
  Responvsive Navbar/src/assets/style.css
  Responvsive Navbar/src/assets/tech-stack/bootstrap.svg
  Responvsive Navbar/src/assets/tech-stack/css.svg
  Responvsive Navbar/src/assets/tech-stack/ejs.svg
  Responvsive Navbar/src/assets/tech-stack/expressjs.svg
  Responvsive Navbar/src/assets/tech-stack/git.svg
  Responvsive Navbar/src/assets/tech-stack/java.svg
  Responvsive Navbar/src/assets/tech-stack/javascript.svg
  Responvsive Navbar/src/assets/tech-stack/materialui.svg
  Responvsive Navbar/src/assets/tech-stack/mongodb.svg
  Responvsive Navbar/src/assets/tech-stack/nodejs.svg
  Responvsive Navbar/src/assets/tech-stack/postman.svg
  Responvsive Navbar/src/assets/tech-stack/python.svg
  Responvsive Navbar/src/assets/tech-stack/react.png
  Responvsive Navbar/src/index.js
Labels: hacktoberfest-accepted, hacktoberfest
